apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: test
  labels:
    environment: test
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      environment: test
  template:
    metadata:
      labels:
        app: backend
        environment: test
    spec:
      containers:
        - image: philophilo/exp
          imagePullPolicy: Always
          name: backend
          ports:
          - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3